### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while calling a Python object when requesting legend graphic

### ISSUE THREAD

**Issue by spike83** [qwc-services/qwc-legend-service#12]
When requesting legend image to some layer I get an error 500 / 503 from the server.

/api/v1/legend/leitungskataster?VERSION=1.3.0&SERVICE=WMS&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&CRS=EPSG%3A2056&SLD_VERSION=1.1.0&LAYER=Sonderbauwerke&TYPE=tooltip

```
spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 7, cores: 4)
[2022-08-03 16:12:45,293] ERROR in app: Exception on /leitungskataster [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.9/site-packages/flask_restx/api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask_restx/resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/srv/qwc_service/./server.py", line 151, in get
    return legend_service.get_legend(
  File "/srv/qwc_service/./legend_service.py", line 92, in get_legend
    permitted_resources = self.permitted_resources(service_name, identity)
  File "/srv/qwc_service/./legend_service.py", line 552, in permitted_resources
    self.collect_restricted_group_layers(
  File "/srv/qwc_service/./legend_service.py", line 591, in collect_restricted_group_layers
    self.collect_restricted_group_layers(
  File "/srv/qwc_service/./legend_service.py", line 591, in collect_restricted_group_layers
    self.collect_restricted_group_layers(
  File "/srv/qwc_service/./legend_service.py", line 591, in collect_restricted_group_layers
    self.collect_restricted_group_layers(
  File "/srv/qwc_service/./legend_service.py", line 591, in collect_restricted_group_layers
    self.collect_restricted_group_layers(
  File "/srv/qwc_service/./legend_service.py", line 591, in collect_restricted_group_layers
    self.collect_restricted_group_layers(
  [Previous line repeated 984 more times]
  File "/srv/qwc_service/./legend_service.py", line 588, in collect_restricted_group_layers
    sublayers.append(sublayer)
RecursionError: maximum recursion depth exceeded while calling a Python object
```

when logging with 
```
592:                self.logger.error("sublayer: %s group_layers: %s" % (sublayer, group_layers))
```

I'm getting the following output:

```
*** uWSGI is running in multiple interpreter mode ***
gracefully (RE)spawned uWSGI master process (pid: 1)
spawned uWSGI worker 1 (pid: 75, cores: 4)
[2022-08-03 16:25:08,546] ERROR in legend_service: sublayer: Abwasser Darstellung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,547] ERROR in legend_service: sublayer: Leitung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,547] ERROR in legend_service: sublayer: Sonderbauwerke Fläche group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,548] ERROR in legend_service: sublayer: Sonderbauwerke group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,548] ERROR in legend_service: sublayer: Abwasser Darstellung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,549] ERROR in legend_service: sublayer: Abwasser Darstellung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,550] ERROR in legend_service: sublayer: Leitung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,550] ERROR in legend_service: sublayer: Sonderbauwerke Fläche group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,550] ERROR in legend_service: sublayer: Abwasser Darstellung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,551] ERROR in legend_service: sublayer: Leitung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,551] ERROR in legend_service: sublayer: Sonderbauwerke Fläche group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,551] ERROR in legend_service: sublayer: Sonderbauwerke group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,552] ERROR in legend_service: sublayer: Schacht group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,552] ERROR in legend_service: sublayer: Some-Leitungen group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,552] ERROR in legend_service: sublayer: Some-Leitungen group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,552] ERROR in legend_service: sublayer: Some-Leitungen group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,553] ERROR in legend_service: sublayer: Some-Leitungen group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,553] ERROR in legend_service: sublayer: Some-Leitungen group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,550] ERROR in legend_service: sublayer: Leitung Eigentum group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,554] ERROR in legend_service: sublayer: Sonderbauwerke Fläche group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
[2022-08-03 16:25:08,554] ERROR in legend_service: sublayer: Sonderbauwerke group_layers: {'Abwasser Darstellung Eigentum': ['Leitung Eigentum', 'Sonderbauwerke Fläche', 'Sonderbauwerke', 'Schacht'], 'Some-Leitungen': ['Some-Leitungen'], 'Leitungskataster': ['Abwasser Darstellung Eigentum', 'Some-Leitungen']}
```
(trucated)

There seems to be an issue building up group layer / sub layer structure.

**Comment by spike83** [comment]
Yes, thanks for the hint.

![image](https://user-images.githubusercontent.com/16322660/182760049-b63f8044-004a-4229-8dad-eddd00af55b1.png)

After I've put the WMS layer top level without the group with same name it works.

From the logs I could see similar issues in ogc-service at this place: https://github.com/qwc-services/qwc-ogc-service/blob/master/ogc_service.py#L565

**Comment by manisandro** [comment]
Yes, generally WMS layer names should be unique.
